basic.forever(function () {
    music.playMelody("F G A F G A F F ", 307)
    music.playMelody("F G A F G A F F ", 307)
    music.playMelody("F G A F G A F F ", 307)
    music.playMelody("C C - - - - - A ", 307)
    music.playMelody("F G A F G A F F ", 307)
    music.playMelody("F G A E F A F F ", 307)
    music.playMelody("F G A F G A F F ", 307)
    music.playMelody("C5 - C5 - C5 - C5 - ", 1200)
    music.playMelody("C5 - C5 - C5 - C5 - ", 1200)
    music.playMelody("C5 - C5 - C5 - C5 - ", 1200)
    music.playMelody("C5 - C5 - C5 - C5 - ", 1200)
    music.playMelody("C D - - - - - C5 ", 432)
    music.playMelody("G A - A - G - A ", 307)
    music.playMelody("- G - A - A G - ", 307)
    music.playMelody("F G A - A - G - ", 307)
    music.playMelody("A - - - - - - - ", 307)
})
