
def on_forever():
    music.play_melody("F G A F G A F F ", 307)
    music.play_melody("F G A F G A F F ", 307)
    music.play_melody("F G A F G A F F ", 307)
    music.play_melody("C C - - - - - A ", 307)
    basic.clear_screen()
    music.play_melody("F G A F G A F F ", 307)
    music.play_melody("F G A E F A F F ", 307)
    music.play_melody("F G A F G A F F ", 307)
    music.play_melody("C5 - C5 - C5 - C5 - ", 1200)
    music.play_melody("C5 - C5 - C5 - C5 - ", 1200)
    music.play_melody("C5 - C5 - C5 - C5 - ", 1200)
    music.play_melody("C5 - C5 - C5 - C5 - ", 1200)
    music.play_melody("C D - - - - - C5 ", 432)
    music.play_melody("G A - A - G - A ", 307)
    music.play_melody("- G - A - A G - ", 307)
    music.play_melody("F G A - A - G - ", 307)
    music.play_melody("A - - - - - - -", 307)
basic.forever(on_forever)
